// HOME State
export const SET_HOME_STATE = 'SET_HOME_STATE'
export const DEFAULT_HOME_STATE = 'DEFAULT_HOME_STATE'

// About STATE
export const SET_ABOUT_STATE = 'SET_ABOUT_STATE'
export const DEFAULT_ABOUT_STATE = 'DEFAULT_ABOUT_STATE'
